# Tells Travis we're running on a Node environment
language: 'node_js'
node_js: '12'

# Deployment information
deploy:
  provider: pages # Tell Travis we want to deploy to Github Pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Will take the environment variable you created on step 5
  repo: cozy/mui-bottom-sheet # Add your username/project_name here
  target_branch: gh-pages # Tell Travis to deploy on the gh-pages branch
  on:
    branch: master # Tell Travis to trigger a deploy only when we push to master
